export const REGION_TRANSITION_DURATION = 1000;
export const MAP_REGION_TRANSITION_DURATION = REGION_TRANSITION_DURATION;
export const NATION_DEFAULT_ID = "0000";
export const PANDEMIC_NAME = "Coronavirus";